name: ts-and-prettier

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm ci

      - name: Copy tsconfig.json
        run: |
          if [ -f tsconfig.json ]; then
            cp tsconfig.json tsconfig.ci.json
          fi

      - name: Check Prettier formatting
        run: npm run check-format

      - name: Check TypeScript compilation
        run: npx tsc --project tsconfig.ci.json --noEmit
